# Generated by Django 2.2.3 on 2019-09-10 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_num', models.IntegerField()),
                ('unit_num', models.IntegerField()),
                ('vin', models.CharField(max_length=17)),
                ('license_num', models.CharField(max_length=25)),
                ('mileage_out', models.IntegerField()),
                ('mileage_in', models.IntegerField()),
                ('state', models.TextField(max_length=250)),
                ('date', models.DateField()),
                ('term', models.CharField(choices=[('W', 'Weekly (7 Days)'), ('BW', 'Bi-Weekly (14 Days)'), ('M', 'Monthly (30 Days)'), ('BM', 'Bi-Monthly (60 Days)')], default='M', max_length=1)),
                ('payment_freq', models.CharField(max_length=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Car')),
            ],
        ),
    ]
