# Generated by Django 2.2.3 on 2019-09-11 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190911_0208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='agreement',
            name='agreement_num',
            field=models.IntegerField(verbose_name='Agreement No.'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='condition',
            field=models.TextField(max_length=250, verbose_name='Condition of Car'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='license_num',
            field=models.CharField(max_length=25, verbose_name='License No.'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='payment_freq',
            field=models.CharField(choices=[('W', 'Weekly (7 Days)'), ('BW', 'Bi-Weekly (14 Days)'), ('M', 'Monthly (30 Days)'), ('BM', 'Bi-Monthly (60 Days)')], default='M', max_length=2, verbose_name='Payment Frequency'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='unit_num',
            field=models.IntegerField(verbose_name='Unit No.'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='vin',
            field=models.CharField(max_length=17, verbose_name='VIN'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Car')),
            ],
        ),
    ]
