# Generated by Django 2.2.3 on 2019-09-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190911_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(verbose_name='Mobile Phone Number')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('license_num', models.CharField(max_length=100, verbose_name='Drivers License No.')),
                ('l_state', models.CharField(max_length=100, verbose_name='License: State')),
                ('l_country', models.CharField(max_length=100, verbose_name='License: Country')),
                ('l_zip', models.CharField(max_length=100, verbose_name='License: Zip Code')),
                ('birth', models.DateField(verbose_name='Birth Date')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='customers',
            field=models.ManyToManyField(to='main_app.Customer'),
        ),
    ]
