# Generated by Django 2.2.3 on 2019-09-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190911_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirFreshener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scent', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='air_fresheners',
            field=models.ManyToManyField(to='main_app.AirFreshener'),
        ),
    ]
